controllers:
    resource: ../src/Controller/
    type: attribute
api_login_check:
    path: /api/login_check
    
login:
   methods: POST
   path: /user/login
   controller: App\Controller\LoginController::login

register:
   path: /user/register
   controller: App\Controller\RegisterController::register

